// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectTripsDB.Models;

#nullable disable

namespace ProjectTripsDB.Migrations
{
    [DbContext(typeof(ProjectTripsDataBase))]
    [Migration("20260311132233_changeLegteKMToLengthKMInDayTrip")]
    partial class changeLegteKMToLengthKMInDayTrip
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Repository.Entities.DayTrip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Accessibility")
                        .HasColumnType("int");

                    b.Property<bool>("AllowRain")
                        .HasColumnType("bit");

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("ApprovedAt")
                        .HasColumnType("date");

                    b.Property<double?>("AverageRating")
                        .HasColumnType("float");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("DayTripTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("HasCommonWeather")
                        .HasColumnType("bit");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("MaxCloudCoverage")
                        .HasColumnType("float");

                    b.Property<double?>("MaxHumidity")
                        .HasColumnType("float");

                    b.Property<double?>("MaxRainProbability")
                        .HasColumnType("float");

                    b.Property<double?>("MaxTemperature")
                        .HasColumnType("float");

                    b.Property<double?>("MaxWindSpeed")
                        .HasColumnType("float");

                    b.Property<double?>("MinTemperature")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int?>("RatingsCount")
                        .HasColumnType("int");

                    b.Property<int?>("RegionId")
                        .HasColumnType("int");

                    b.Property<string>("RejectReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<double>("TotalDurationHours")
                        .HasColumnType("float");

                    b.Property<double>("TotalLengthKM")
                        .HasColumnType("float");

                    b.Property<string>("TripHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DayTripTypeId");

                    b.HasIndex("RegionId");

                    b.HasIndex("TripHash")
                        .IsUnique();

                    b.ToTable("DayTrips", (string)null);
                });

            modelBuilder.Entity("Repository.Entities.DayTripItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DayTripId")
                        .HasColumnType("int");

                    b.Property<double>("EstimatedDuration")
                        .HasColumnType("float");

                    b.Property<int>("ItemType")
                        .HasColumnType("int");

                    b.Property<int?>("Mode")
                        .HasColumnType("int");

                    b.Property<int>("OrderInTrip")
                        .HasColumnType("int");

                    b.Property<int?>("PlaceId")
                        .HasColumnType("int");

                    b.Property<int?>("RouteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DayTripId");

                    b.HasIndex("PlaceId");

                    b.HasIndex("RouteId");

                    b.ToTable("DayTripItems", (string)null);
                });

            modelBuilder.Entity("Repository.Entities.DayTripType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DayTripTypes", (string)null);
                });

            modelBuilder.Entity("Repository.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<int>("ItemType")
                        .HasColumnType("int");

                    b.Property<int?>("PlaceId")
                        .HasColumnType("int");

                    b.Property<int?>("RouteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("PlaceId");

                    b.HasIndex("RouteId");

                    b.ToTable("Images", (string)null);
                });

            modelBuilder.Entity("Repository.Entities.Place", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Accessibility")
                        .HasColumnType("int");

                    b.Property<bool>("AllowRain")
                        .HasColumnType("bit");

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("ApprovedAt")
                        .HasColumnType("date");

                    b.Property<double?>("AverageRating")
                        .HasColumnType("float");

                    b.Property<int?>("AverageStayMinutes")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("ClosingTime")
                        .HasColumnType("time");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasCommonWeather")
                        .HasColumnType("bit");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<double?>("MaxCloudCoverage")
                        .HasColumnType("float");

                    b.Property<double?>("MaxHumidity")
                        .HasColumnType("float");

                    b.Property<double?>("MaxRainProbability")
                        .HasColumnType("float");

                    b.Property<double?>("MaxTemperature")
                        .HasColumnType("float");

                    b.Property<double?>("MaxWindSpeed")
                        .HasColumnType("float");

                    b.Property<double?>("MinTemperature")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("OpeningTime")
                        .HasColumnType("time");

                    b.Property<int>("PlaceTypeId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int?>("RatingsCount")
                        .HasColumnType("int");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.Property<string>("RejectReason")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("PlaceTypeId");

                    b.HasIndex("RegionId");

                    b.ToTable("Places", (string)null);
                });

            modelBuilder.Entity("Repository.Entities.PlaceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PlaceTypes", (string)null);
                });

            modelBuilder.Entity("Repository.Entities.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ParentRegionId")
                        .HasColumnType("int");

                    b.Property<string>("RegionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ParentRegionId");

                    b.ToTable("Regions", (string)null);
                });

            modelBuilder.Entity("Repository.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ContentType")
                        .HasColumnType("int");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<int?>("DayTripId")
                        .HasColumnType("int");

                    b.Property<int?>("PlaceId")
                        .HasColumnType("int");

                    b.Property<int?>("RouteId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DayTripId");

                    b.HasIndex("PlaceId");

                    b.HasIndex("RouteId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews", (string)null);
                });

            modelBuilder.Entity("Repository.Entities.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Accessibility")
                        .HasColumnType("int");

                    b.Property<bool>("AllowRain")
                        .HasColumnType("bit");

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("ApprovedAt")
                        .HasColumnType("date");

                    b.Property<double?>("AverageRating")
                        .HasColumnType("float");

                    b.Property<TimeOnly>("ClosingTime")
                        .HasColumnType("time");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<double>("DurationMinutes")
                        .HasColumnType("float");

                    b.Property<double>("EndLatitude")
                        .HasColumnType("float");

                    b.Property<double>("EndLongitude")
                        .HasColumnType("float");

                    b.Property<bool>("HasCommonWeather")
                        .HasColumnType("bit");

                    b.Property<double>("LengthKm")
                        .HasColumnType("float");

                    b.Property<double?>("MaxCloudCoverage")
                        .HasColumnType("float");

                    b.Property<double?>("MaxHumidity")
                        .HasColumnType("float");

                    b.Property<double?>("MaxRainProbability")
                        .HasColumnType("float");

                    b.Property<double?>("MaxTemperature")
                        .HasColumnType("float");

                    b.Property<double?>("MaxWindSpeed")
                        .HasColumnType("float");

                    b.Property<double?>("MinTemperature")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("OpeningTime")
                        .HasColumnType("time");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int?>("RatingsCount")
                        .HasColumnType("int");

                    b.Property<int?>("RegionId")
                        .HasColumnType("int");

                    b.Property<string>("RejectReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RouteTypeId")
                        .HasColumnType("int");

                    b.Property<double>("StartLatitude")
                        .HasColumnType("float");

                    b.Property<double>("StartLongitude")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("RegionId");

                    b.HasIndex("RouteTypeId");

                    b.ToTable("Routes", (string)null);
                });

            modelBuilder.Entity("Repository.Entities.RoutePoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("EstimatedStayMinutes")
                        .HasColumnType("float");

                    b.Property<bool>("IsEndPoint")
                        .HasColumnType("bit");

                    b.Property<bool>("IsStartPoint")
                        .HasColumnType("bit");

                    b.Property<int>("OrderInRoute")
                        .HasColumnType("int");

                    b.Property<int>("RouteId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RouteId");

                    b.ToTable("RoutePoints", (string)null);
                });

            modelBuilder.Entity("Repository.Entities.RouteType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RouteTypes", (string)null);
                });

            modelBuilder.Entity("Repository.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RefreshTokenCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("RefreshTokenRevoked")
                        .HasColumnType("bit");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateOnly(2026, 3, 11),
                            Email = "Admin@gmail.com",
                            FirstName = "Admin",
                            IsActive = true,
                            LastName = "Admin",
                            Password = "Admin#613",
                            RefreshTokenCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RefreshTokenRevoked = false,
                            Role = 1
                        });
                });

            modelBuilder.Entity("Repository.Entities.DayTrip", b =>
                {
                    b.HasOne("Repository.Entities.User", "User")
                        .WithMany("DayTrips")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repository.Entities.DayTripType", "DayTripType")
                        .WithMany("DayTrips")
                        .HasForeignKey("DayTripTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repository.Entities.Region", "Region")
                        .WithMany("DayTrips")
                        .HasForeignKey("RegionId");

                    b.Navigation("DayTripType");

                    b.Navigation("Region");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Repository.Entities.DayTripItem", b =>
                {
                    b.HasOne("Repository.Entities.DayTrip", "DayTrip")
                        .WithMany("DayTripItems")
                        .HasForeignKey("DayTripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repository.Entities.Place", "Place")
                        .WithMany("DayTripItems")
                        .HasForeignKey("PlaceId");

                    b.HasOne("Repository.Entities.Route", "Route")
                        .WithMany("DayTripItems")
                        .HasForeignKey("RouteId");

                    b.Navigation("DayTrip");

                    b.Navigation("Place");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("Repository.Entities.Image", b =>
                {
                    b.HasOne("Repository.Entities.User", "User")
                        .WithMany("Images")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Repository.Entities.Place", "Place")
                        .WithMany("Images")
                        .HasForeignKey("PlaceId");

                    b.HasOne("Repository.Entities.Route", "Route")
                        .WithMany("Images")
                        .HasForeignKey("RouteId");

                    b.Navigation("Place");

                    b.Navigation("Route");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Repository.Entities.Place", b =>
                {
                    b.HasOne("Repository.Entities.User", "User")
                        .WithMany("Places")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repository.Entities.PlaceType", "PlaceType")
                        .WithMany("Places")
                        .HasForeignKey("PlaceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repository.Entities.Region", "Region")
                        .WithMany("Places")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlaceType");

                    b.Navigation("Region");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Repository.Entities.Region", b =>
                {
                    b.HasOne("Repository.Entities.Region", "ParentRegion")
                        .WithMany("SubRegions")
                        .HasForeignKey("ParentRegionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentRegion");
                });

            modelBuilder.Entity("Repository.Entities.Review", b =>
                {
                    b.HasOne("Repository.Entities.DayTrip", "DayTrip")
                        .WithMany("Reviews")
                        .HasForeignKey("DayTripId");

                    b.HasOne("Repository.Entities.Place", "Place")
                        .WithMany("Reviews")
                        .HasForeignKey("PlaceId");

                    b.HasOne("Repository.Entities.Route", "Route")
                        .WithMany("Reviews")
                        .HasForeignKey("RouteId");

                    b.HasOne("Repository.Entities.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DayTrip");

                    b.Navigation("Place");

                    b.Navigation("Route");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Repository.Entities.Route", b =>
                {
                    b.HasOne("Repository.Entities.User", "User")
                        .WithMany("Routes")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repository.Entities.Region", "Region")
                        .WithMany("Routes")
                        .HasForeignKey("RegionId");

                    b.HasOne("Repository.Entities.RouteType", "RouteType")
                        .WithMany("Routes")
                        .HasForeignKey("RouteTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");

                    b.Navigation("RouteType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Repository.Entities.RoutePoint", b =>
                {
                    b.HasOne("Repository.Entities.Route", "Route")
                        .WithMany("RoutePoints")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");
                });

            modelBuilder.Entity("Repository.Entities.DayTrip", b =>
                {
                    b.Navigation("DayTripItems");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Repository.Entities.DayTripType", b =>
                {
                    b.Navigation("DayTrips");
                });

            modelBuilder.Entity("Repository.Entities.Place", b =>
                {
                    b.Navigation("DayTripItems");

                    b.Navigation("Images");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Repository.Entities.PlaceType", b =>
                {
                    b.Navigation("Places");
                });

            modelBuilder.Entity("Repository.Entities.Region", b =>
                {
                    b.Navigation("DayTrips");

                    b.Navigation("Places");

                    b.Navigation("Routes");

                    b.Navigation("SubRegions");
                });

            modelBuilder.Entity("Repository.Entities.Route", b =>
                {
                    b.Navigation("DayTripItems");

                    b.Navigation("Images");

                    b.Navigation("Reviews");

                    b.Navigation("RoutePoints");
                });

            modelBuilder.Entity("Repository.Entities.RouteType", b =>
                {
                    b.Navigation("Routes");
                });

            modelBuilder.Entity("Repository.Entities.User", b =>
                {
                    b.Navigation("DayTrips");

                    b.Navigation("Images");

                    b.Navigation("Places");

                    b.Navigation("Reviews");

                    b.Navigation("Routes");
                });
#pragma warning restore 612, 618
        }
    }
}
